### ISSUE TITLE
PR from-branch-to-own-master-branch update behavior

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4001-AY2122S1/forum#10]
HI Prof Damith,

![image](https://user-images.githubusercontent.com/43993134/132327157-1f1f07a0-be8d-47dd-a7e6-4d7820eb7c6b.png)

When I had merged the feature1 branch to master branch in the fork, opening the sourceTree client, no blue pull arrow appear automatically? Even if I checkout the master branch?

Why is this? How do we know there is a change in the fork then, if we did not first visit the remote site? 

Next, after I checkout the master branch first, I did a manual pull, then I see the proper updated display:
![image](https://user-images.githubusercontent.com/43993134/132327873-3ff9484d-707d-4daa-990c-2bcc379f4014.png)

My last question is, must I checkout the master branch first in my local repo in the above step? What happens if I am at the feature1 branch locally when I did the pull?

Thank you!

**Comment by damithc** [comment]
@gweeyc In some cases SourceTree might not have the latest data from the remote repository. You can use the Fetch feature to download the latest Git data without doing any change to the local copy. In fact Pull = Fetch + Merge.

If you pull the master branch while in feature1 branch, Git will also merge the new master branch to your feature1 branch. As mentioned above, Pull = Fetch + Merge. 
That's why it is safe to checkout the branch before you pull, to avoid unexpected merges.

**Comment by gweeyc** [comment]
Thanks and noted!

**Comment by gweeyc** [comment]
Thanks and noted!
